input_dir: "input"
save_dir: "output"
best_model_dir: "best_models"

# train_biencoder.py
train_biencoder:
  model_name: "dunzhang/stella_en_1.5B_v5"
  input_name: "data_kd.csv"
  output_dir: "output_bi_1.5B"
  is_lora: true
  load_in_4bit: false
  mini_batch_size: 4
  seed: 42
  lora_config:
    r: 48
    lora_alpha: 96
  hard_negative_params:
    range_min: 512
    num_negatives: 2
    batch_size: 32
  train_args:
    num_train_epochs: 1.0
    per_device_train_batch_size: 40
    per_device_eval_batch_size: 40
    learning_rate: 0.001
    warmup_steps: 0
    eval_strategy: steps
    save_only_model: true
    eval_steps: 2
    metric_for_best_model: val_cosine_recall@100
    load_best_model_at_end: true
    greater_is_better: true
    save_strategy: steps
    save_steps: 2
    lr_scheduler_type: "cosine"
    save_total_limit: 1
    logging_steps: 1
    report_to: wandb
    bf16: true
